### PR TITLE
Update Glossary.md

### PR DESCRIPTION
**Pull request by m00sey**
adds formatting changes, some typo fixes.

### CODE REVIEW

**Comment by henkvancann** [comment]
Hi Kevin, 
Thx for your contributions.
Have you pulled the Glossary.md before the edits? The PR 141 has also edits to the Glossary, so maybe you could resolve those upfront?
https://github.com/henkvancann/keri/blob/master/docs/Glossary.md 
Best, Henk

**Comment by m00sey** [comment]
Sam approved the changes in #141 so I merged it in. I'll update this in a little bit.

**Comment by henkvancann** [comment]
> Sam approved the changes in #141 so I merged it in. I'll update this in a little bit.

Great, I just have to get use to the git update process with multiple editors I guess

**Comment by SmithSamuelM** [comment]
I am happy to not approve edits but merely comment. If that avoids confusion. Sorry if I stepped in the rice bowl.

**Pull request merged**
